---
- name: Install and configure Redis on Debian 12
  hosts: debian_servers
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Redis server
      apt:
        name: redis-server
        state: present

    - name: Ensure Redis service is started and enabled
      service:
        name: redis-server
        state: started
        enabled: yes

    - name: Check Redis service status
      command: systemctl status redis-server
      register: redis_status
      changed_when: false
      failed_when: false

    - name: Print Redis service status
      debug:
        msg: "{{ redis_status.stdout }}"

    - name: Modify Redis configuration file
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^#?bind '
        line: 'bind 127.0.0.1'
      notify: Restart Redis

    - name: Check if Redis port 6379 is already in use
      command: netstat -tuln | grep ':6379'
      register: port_check
      failed_when: false

    - name: Print port check result
      debug:
        msg: "{{ port_check.stdout }}"

    - name: Ensure Redis service is restarted if not running
      service:
        name: redis-server
        state: restarted
      when: "'Active: active (running)' not in redis_status.stdout"

    - name: Print the last 50 lines of Redis log for further debugging
      command: tail -n 50 /var/log/redis/redis-server.log
      register: redis_log
      failed_when: false

    - name: Print Redis log
      debug:
        msg: "{{ redis_log.stdout }}"

  handlers:
    - name: Restart Redis
      service:
        name: redis-server
        state: restarted
