---
# Playbook to install Redis on Debian 12, add the official Redis repository,
# and display the installed Redis server version.

- name: Install Redis on Debian 12
  hosts: all
  become: true
  tasks:

    - name: Add the Redis GPG key
      # This task adds the GPG key for the Redis package repository to the system's keyring.
      ansible.builtin.shell:
        cmd: curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg

    - name: Add the Redis repository to sources list
      # This task adds the Redis package repository to the system's sources list.
      ansible.builtin.shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list

    - name: Update the package list
      # This task updates the package list to include packages from the newly added Redis repository.
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Redis server
      # This task installs the Redis server package.
      ansible.builtin.apt:
        name: redis-server
        state: present

    - name: Ensure Redis service is started and enabled
      # This task ensures that the Redis service is running and enabled to start at boot.
      ansible.builtin.service:
        name: redis-server
        state: started
        enabled: yes

    - name: Show Redis server version
      # This task retrieves and displays the installed Redis server version.
      ansible.builtin.command:
        cmd: redis-server --version
      register: redis_version_output

    - name: Display Redis server version
      # This task displays the version of Redis that was installed.
      ansible.builtin.debug:
        msg: "Installed Redis version: {{ redis_version_output.stdout }}"
